version: '3'

services:
  web:
    image: nginx:alpine
    container_name: angular_frontend
    restart: always
    ports:
      - "4200:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    depends_on:
      - phpmyadmin
    networks:
      - dev-env

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
    depends_on:
      - mariadb
    volumes:
      - ./backend:/var/www/html
    networks:
      - dev-env

  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'secret'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'secret'
      MYSQL_DATABASE: 'Classification'
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    volumes:
      - mysqldata:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3306:3306
    networks:
      - dev-env

volumes:
  mysqldata: {}

networks:
  dev-env: {}