version: '3.8'

services:
  php-backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8080:80"
    environment:
      DB_HOST: mariadb
      DB_USER: root
      DB_PASS: secret
      DB_NAME: Classification
    depends_on:
      - mariadb
    networks:
      - dev-env
  
  angular_frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: angular_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - php-backend
    networks:
      - dev-env
  
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: Classification
    ports:
      - "3306:3306"
    volumes:
      - ./backend/DB/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - dev-env

networks:
  dev-env:
    driver: bridge
